# Performs a full test of the package within production environment.

name: CI | End-to-End RunPod Python Tests

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build and push mock-worker Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Clone and patch mock-worker
        run: |
          git clone https://github.com/runpod-workers/mock-worker
          echo "git+https://github.com/runpod/runpod-python.git@${{ github.sha }}" > mock-worker/builder/requirements.txt

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define Docker Tag
        id: docker_tag
        run: echo "DOCKER_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build -t ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMG }}:${{ env.DOCKER_TAG }} -f mock-worker/Dockerfile mock-worker
          docker push ${{ vars.DOCKERHUB_REPO }}/${{ vars.DOCKERHUB_IMG }}:${{ env.DOCKER_TAG }}

  test:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        uses: direlines/runpod-test-runner@v1.5
        with:
          image-tag: ${{ needs.build.outputs.docker_tag }}
          runpod-api-key: ${{ secrets.RUNPOD_API_KEY }}
