name: CI | Unit Tests

on:
  push:
    branches:
      - "**"
      - "main"
      - "!main-ci"
      - "!release"

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  run_tests:
    strategy:
      matrix:
        python-version: [3.10.12, 3.11.0, 3.12.0-beta.3]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies (3.9 & 3.10.12 & 3.11.0)
        if: matrix.python-version == '3.10.12' || matrix.python-version == '3.11.0'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-timeout

      - name: Install Dependencies (3.12.0-beta.3)
        if: matrix.python-version == '3.12.0-beta.3'
        run: |
          python -m pip install --upgrade pip
          pip install --global-option build --global-option --force -r requirements.txt
          pip install pytest
          pip install pytest-timeout

      - name: Run Tests
        run: |
          pytest --timeout=60 --timeout_method=thread
